LOADING THE DATA

In [11]:
#Importing 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import json

In [20]:
#loading fake_dataset
with open('../data/data.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

fake_df1 = pd.DataFrame(data)
fake_df2=pd.read_csv('../data/synthetic_fake_reviews.csv',)

In [21]:
#loading genuine_dataset
genuine_df1=pd.read_csv('../data/G_review1.csv')
genuine_df2=pd.read_csv('../data/G_review2.csv')

In [41]:
#importing reusable functions
import sys
import os

# Add src folder to Python path
sys.path.append(os.path.abspath("../src"))


from pre import get_length_type, add_feature_columns,generate_date,detect_slang

In [ ]:
fake_df2.head()

,review_id,review_text,label,fake_type,language_style,domain,length_type,word_count,synthetic
0,SYN_00001,"Dherai kharaab service, I hate this salon, sta...",fake,negative_attack,code_mixed,services,very_short,12,True
1,SYN_00002,"Bank ko customer care bhayaanak thiyo, I didn'...",fake,negative_attack,code_mixed,services,very_short,14,True
2,SYN_00003,"Repair shop ko price dherai high cha, I won't ...",fake,negative_attack,code_mixed,services,very_short,13,True
3,SYN_00004,"Hospital ko doctor haraamkhor thiye, I won't g...",fake,negative_attack,code_mixed,services,very_short,12,True
4,SYN_00005,"Salon ko hair stylist bhayaanak skilled thiyo,...",fake,negative_attack,code_mixed,services,very_short,14,True

In [22]:

genuine_df = pd.concat([genuine_df1, genuine_df2], ignore_index=True)

In [23]:

fake_df1['word_count'] = fake_df1['review_text'].apply(lambda x: len(str(x).split()))
genuine_df['word_count'] = genuine_df['review_text'].apply(lambda x: len(str(x).split()))

In [24]:
fake_df1["length_type"] = fake_df1["word_count"].apply(get_length_type)
genuine_df["length_type"] = genuine_df["word_count"].apply(get_length_type)

In [25]:
# Drop multiple columns
fake_df2.drop(columns=['review_id', 'label', 'synthetic','length_type'], inplace=True)
fake_df2.head()

,review_text,fake_type,language_style,domain,word_count
0,"Dherai kharaab service, I hate this salon, sta...",negative_attack,code_mixed,services,12
1,"Bank ko customer care bhayaanak thiyo, I didn'...",negative_attack,code_mixed,services,14
2,"Repair shop ko price dherai high cha, I won't ...",negative_attack,code_mixed,services,13
3,"Hospital ko doctor haraamkhor thiye, I won't g...",negative_attack,code_mixed,services,12
4,"Salon ko hair stylist bhayaanak skilled thiyo,...",negative_attack,code_mixed,services,14

In [26]:
fake_df1.head()

,review_text,rating,date,language_style,has_slang,slang_count,domain,fake_type,word_count,length_type
0,"yo product lastai ramro cha, life ma yesto qua...",5,2023-07-12,romanized_nepali,1.0,2.0,product,NaN,14,short
1,This hotel is absolutely the best in the entir...,5,2024-03-22,english,0.0,0.0,hotel_restaurant,NaN,19,short
2,food ekdum dami cha ani service pani world cla...,5,2023-11-08,code_mixed,1.0,1.0,food,NaN,15,short
3,"worst motorcycle ever, ekdum kharab, paisa was...",1,2022-09-15,code_mixed,0.0,0.0,transportation,NaN,11,short
4,"yo service sabai vanda ramro, ekdum profession...",5,2024-01-30,romanized_nepali,1.0,1.0,services,NaN,12,short

In [27]:
fake_df2["length_type"] = fake_df2["word_count"].apply(get_length_type)
fake_df2 = add_feature_columns(fake_df2)
fake_df2.head()

,review_text,fake_type,language_style,domain,word_count,length_type,rating,date,has_slang,slang_count
0,"Dherai kharaab service, I hate this salon, sta...",negative_attack,code_mixed,services,12,short,1,2023-10-08,False,0
1,"Bank ko customer care bhayaanak thiyo, I didn'...",negative_attack,code_mixed,services,14,short,3,2024-05-25,False,0
2,"Repair shop ko price dherai high cha, I won't ...",negative_attack,code_mixed,services,13,short,1,2022-07-12,False,0
3,"Hospital ko doctor haraamkhor thiye, I won't g...",negative_attack,code_mixed,services,12,short,1,2023-11-08,False,0
4,"Salon ko hair stylist bhayaanak skilled thiyo,...",negative_attack,code_mixed,services,14,short,1,2024-05-21,False,0

In [28]:
fake_df = pd.concat([fake_df1, fake_df2], ignore_index=True)
fake_df.head()

,review_text,rating,date,language_style,has_slang,slang_count,domain,fake_type,word_count,length_type
0,"yo product lastai ramro cha, life ma yesto qua...",5,2023-07-12,romanized_nepali,1.0,2.0,product,NaN,14,short
1,This hotel is absolutely the best in the entir...,5,2024-03-22,english,0.0,0.0,hotel_restaurant,NaN,19,short
2,food ekdum dami cha ani service pani world cla...,5,2023-11-08,code_mixed,1.0,1.0,food,NaN,15,short
3,"worst motorcycle ever, ekdum kharab, paisa was...",1,2022-09-15,code_mixed,0.0,0.0,transportation,NaN,11,short
4,"yo service sabai vanda ramro, ekdum profession...",5,2024-01-30,romanized_nepali,1.0,1.0,services,NaN,12,short

In [29]:
fake_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2374 entries, 0 to 2373
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   review_text     2374 non-null   str
 1   rating          2374 non-null   int64
 2   date            2326 non-null   str
 3   language_style  2374 non-null   str
 4   has_slang       2305 non-null   float64
 5   slang_count     2305 non-null   float64
 6   domain          2354 non-null   str
 7   fake_type       2188 non-null   str
 8   word_count      2374 non-null   int64
 9   length_type     2374 non-null   str
dtypes: float64(2), int64(2), str(6)
memory usage: 185.6 KB

In [30]:
# dropping fake_type col before merging with genuine_df
fake_df.drop(columns=["fake_type"], inplace=True)

In [31]:
#labeling genuine reviews as 0 and fake reviews as 1
genuine_df['label'] = 0
fake_df['label'] = 1

In [48]:
#merging fake_df and genuine_df
df = pd.concat([genuine_df, fake_df], ignore_index=True)
df.head()

,review_text,rating,date,language_style,has_slang,slang_count,domain,word_count,length_type,label
0,Kwati soup traditional restaurant — 9 types be...,4,10/15/2023,english,0.0,0.0,food,33,medium,0
1,Fuel gauge inaccurate wrong reading,2,12/19/2023,english,0.0,0.0,transportation,5,very_short,0
2,Gym ma personal training session 5 wota try ga...,4,8/2/2024,code_mixed,0.0,0.0,services,76,long,0
3,Tailor worth it ... Service was a bit slow but...,5,11/21/2024,english,0.0,0.0,services,11,short,0
4,Sahayatri ma peak time 😐😊😍 surcharge dherai bh...,3,8/21/2022,romanized_nepali,0.0,0.0,transportation,17,short,0

In [51]:
df = df.sample(frac=1, random_state=42).reset_index(drop=True)  # shuffle the dataset
df.head()

,review_text,rating,date,language_style,has_slang,slang_count,domain,word_count,length_type,label
0,Taximandu 464 tasty enough ngl It was quite a ...,5,5/2/2023,english,0.0,0.0,transportation,24,short,0
1,"I went to this restaurant with my friends, and...",4,2024-07-05,code_mixed,0.0,0.0,hotel_restaurant,81,long,1
2,Numberplate great quality overall ngl Recived ...,4,7/28/2023,english,0.0,0.0,transportation,21,short,0
3,Stayed here for two nights and it was a total ...,1,2024-06-22,english,NaN,NaN,NaN,28,short,1
4,"chowmein ekdum jhyau thiyo, spice level pani p...",5,2023-07-04,code_mixed,1.0,1.0,food,12,short,1

In [53]:
#checking null values
df.isnull().sum()

review_text        0
rating             0
date              48
language_style     0
has_slang         69
slang_count       69
domain            20
word_count         0
length_type        0
label              0
dtype: int64

In [35]:
df.to_csv('../data/processed_reviews.csv', index=False)

In [40]:
#to check count of each unique value in has_slang column
df['has_slang'].value_counts()

has_slang
0.0    2646
1.0    1843
Name: count, dtype: int64

In [54]:
#fixing null val in date

df["date"] = df["date"].fillna(df.apply(lambda _: generate_date(), axis=1))
df.date.isnull().sum()

np.int64(0)

In [55]:
#only fixing null val in has_slang column
null_slang_mask = df["has_slang"].isnull()
slang_results   = df.loc[null_slang_mask, "review_text"].apply(detect_slang)
df.loc[null_slang_mask, "has_slang"]   = slang_results.apply(lambda x: x[0]).astype(int)
df.loc[null_slang_mask, "slang_count"] = slang_results.apply(lambda x: x[1]).astype(int)
df.has_slang.isnull().sum()

np.int64(0)

In [57]:
df = df.dropna(subset=["domain"])
df.isnull().sum()

review_text       0
rating            0
date              0
language_style    0
has_slang         0
slang_count       0
domain            0
word_count        0
length_type       0
label             0
dtype: int64